server:
  port: 8761

spring:
  application:
    name: @pom.artifactId@
  security:
    user:
      name: root
      password: root
      roles: root

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
  server:
    enable-self-preservation: false
  instance:
    hostname: localhost
    prefer-ip-address: true